# Lineare Algebra Playground

In [2]:
import numpy as np

In [6]:
spalenV = np.array([[1], [2], [3]])
zeilenV = np.array([1,3,3])

print(spalenV)
print(zeilenV)

[[1]
 [2]
 [3]]
[1 3 3]


In [22]:
# Übung 2.1
A = np.array([[1,2], [3,4], [-1,2]])
B = np.array([[1,1,-1]])
C = np.array([[-2],[2]])
D = np.array([[2,4],[4,2]])

print('AC', np.dot(A,C))
print('AD', np.dot(A,D))
print('BA', B@A)
print(C)
print(B)
print('CB', np.dot(C,B))

AC [[2]
 [2]
 [6]]
AD [[10  8]
 [22 20]
 [ 6  0]]
BA [[5 4]]
[[-2]
 [ 2]]
[[ 1  1 -1]]
CB [[-2 -2  2]
 [ 2  2 -2]]
