# Linal Übungen

In [1]:
import numpy as np

### Übung 2.3
Bestimmen Sie die Inverse der Matrizen

A = np.array([[5,2], [-7, -3]])
B = np.array([[1,2], [3,4]])

Ia = np.linalg.inv(A)
Ib = np.linalg.inv(B)
Ia, Ib

### Übung 2.5: Finden Sie die Lösung des Gleichungssystems

```
−3y−2z = 1
x−4y −2z = 0
−3x+4y+z = 1
```

In [6]:
A = np.array([[0, -3, -2], [1, -4, -2], [-3, 4, 1]])
b = np.array([[1], [0], [1]])
A, b

(array([[ 0, -3, -2],
        [ 1, -4, -2],
        [-3,  4,  1]]),
 array([[1],
        [0],
        [1]]))

In [7]:
# def: x = A1 * b
x = np.linalg.inv(A).dot(b)
x

array([[ 2.],
       [ 3.],
       [-5.]])

## Determinante berechnen

In [11]:
A = np.array([[1,2], [2,-3]])
B = np.array([[1,-2], [3,1]])
C = np.array([[2,1], [2, 1]])

detA = np.linalg.det(A)
detB = np.linalg.det(B)
detC = np.linalg.det(C)
detA, detB, detC

(-7.000000000000001, 7.000000000000001, 0.0)

## Norm berechnen

In [12]:
u = np.array([[1], [0]])
v = np.array([[1], [2], [-4]])
u, v

(array([[1],
        [0]]),
 array([[ 1],
        [ 2],
        [-4]]))

In [13]:
L1u = np.linalg.norm(u, 1)
L2u = np.linalg.norm(u)
L1u, L2u

(1.0, 1.0)

In [15]:
L1v = np.linalg.norm(v, 1)
L2v = np.linalg.norm(v)
L1v, L2v

(7.0, 4.58257569495584)

# Skalarprodukt berechnen

In [16]:
u = np.array([[1], [0]])
v = np.array([[2], [3]])
u, v

(array([[1],
        [0]]),
 array([[2],
        [3]]))

In [21]:
winkelUV = np.arccos((u.T).dot(v) / (np.linalg.norm(u) * np.linalg.norm(v)))
winkelUV

array([[0.98279372]])

In [23]:
winkelUV = np.vdot(u, v)
winkelUV

2

# Drehung

In [34]:
v = np.array([[1], [2]])
alpha = np.radians(30)

R = np.array([[np.cos(alpha), -np.sin(alpha)], [np.sin(alpha), np.cos(alpha)]])
R

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [35]:
vAbgebildet = R.dot(v)
vAbgebildet

array([[-0.1339746 ],
       [ 2.23205081]])

In [36]:
# test
vAbgebildet2 = np.array([[-1 + (np.sqrt(3) / 2)], [1/2 + np.sqrt(3)]])
vAbgebildet2

array([[-0.1339746 ],
       [ 2.23205081]])

In [37]:
A = np.array([[2,1], [4,5], [7,9]])
Ai = A.T
A, Ai

(array([[2, 1],
        [4, 5],
        [7, 9]]),
 array([[2, 4, 7],
        [1, 5, 9]]))

In [38]:
B = np.array([[4,3], [1,2]])
detB = np.linalg.det(B)
B, detB

(array([[4, 3],
        [1, 2]]),
 4.999999999999999)

In [40]:
P = np.array([[4], [3], [2]])
L1 = np.linalg.norm(P, 1)
L2 = np.linalg.norm(P, 2)
P, L1, L2

(array([[4],
        [3],
        [2]]),
 9.0,
 5.385164807134505)

5.385164807134504

In [44]:
ret = np.array([[1,2], [3,4]]) + np.array([[1, 2], [2]])
ret

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.