# UV-Decomposition

In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True)

In [3]:
# initialisiere M und U,V
M = np.array([
    [np.nan,np.nan,7,np.nan,10],
    [9,np.nan,6,np.nan,np.nan],
    [1,10,np.nan,3,np.nan],
    [9,np.nan,np.nan,5,10],
    [np.nan,4,10,np.nan,3],
    [5,2,np.nan,9,6]
])
n = 2
U = np.ones((M.shape[0],n))
V = np.ones((n,M.shape[1]))

In [4]:
# root mean squared error
def rmse(A, B):
    return np.sqrt(np.nanmean(np.power((A - B),2)))

In [5]:
# minimiere U[r,s]
def minimize_U(M, U, V, r, s):       
    U = U.copy()
    a = 0
    b = 0
    for j in range(M.shape[1]):        
        if np.isnan(M[r,j]):
            continue
        a += V[s,j] * (M[r,j] - sum(U[r,k] * V[k,j] for k in range(U.shape[1]) if k != s))
        b += np.power(V[s,j],2) 
    U[r,s] = a/b
    return U


In [6]:
# minimiere V[r,s]
def minimize_V(M, U, V, r, s):       
    V = V.copy()
    a = 0
    b = 0
    for i in range(M.shape[0]):        
        if np.isnan(M[i,s]):
            continue
        a += U[i,r] * (M[i,s] - sum(U[i,k] * V[k,s] for k in range(V.shape[0]) if k != r))
        b += np.power(U[i,r],2) 
    V[r,s] = a/b
    return V

In [7]:
init_value = np.sqrt(np.nanmean(M)/2)
init_value = 1
U = np.ones((M.shape[0],2)) * init_value
V = np.ones((2,M.shape[1])) * init_value

In [8]:
U @ V

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [9]:
U = minimize_U(M, U, V, 0, 0)

In [10]:
U

array([[7.5, 1. ],
       [1. , 1. ],
       [1. , 1. ],
       [1. , 1. ],
       [1. , 1. ],
       [1. , 1. ]])

In [11]:
U @ V

array([[8.5, 8.5, 8.5, 8.5, 8.5],
       [2. , 2. , 2. , 2. , 2. ],
       [2. , 2. , 2. , 2. , 2. ],
       [2. , 2. , 2. , 2. , 2. ],
       [2. , 2. , 2. , 2. , 2. ],
       [2. , 2. , 2. , 2. , 2. ]])

In [12]:
V = minimize_V(M, U, V, 0, 0)

In [13]:
V

array([[5., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
U @ V

array([[38.5,  8.5,  8.5,  8.5,  8.5],
       [ 6. ,  2. ,  2. ,  2. ,  2. ],
       [ 6. ,  2. ,  2. ,  2. ,  2. ],
       [ 6. ,  2. ,  2. ,  2. ,  2. ],
       [ 6. ,  2. ,  2. ,  2. ,  2. ],
       [ 6. ,  2. ,  2. ,  2. ,  2. ]])

In [15]:
# UV-Decomposition Algorithmus
def UV_decomposition(M, k, delta_treshold=0.001, max_iter=50):
    init_value = np.sqrt(np.nanmean(M)/k)
    U = np.ones((M.shape[0],k)) * init_value
    V = np.ones((k,M.shape[1])) * init_value
    
    delta = np.inf
    last_error = np.inf
    i = 0
    while delta > delta_treshold and i < max_iter:
        for r in range(U.shape[0]):
            for s in range(U.shape[1]):
                U = minimize_U(M, U, V, r, s)
            print(f'{i:>2}: {rmse(M,U @ V):.7}', end="\r")

        for r in range(V.shape[0]):
            for s in range(V.shape[1]):
                V = minimize_V(M, U, V, r, s)
            print(f'{i:>2}: {rmse(M,U @ V):.7}', end="\r")

        P = U @ V
        error = rmse(M,P)
        delta = last_error - error
        last_error = error
        print(f'{i:>2}: {error:.7}')
        i += 1
    return U, V

In [16]:
U, V = UV_decomposition(M, 2)

 0: 2.518866
 1: 2.106281
 2: 1.327567
 3: 0.9226152
 4: 0.6568622
 5: 0.5642329
 6: 0.5158006
 7: 0.4798756
 8: 0.4495072
 9: 0.4228953
10: 0.3994213
11: 0.3786788
12: 0.3602949
13: 0.3439297
14: 0.3292817
15: 0.3160961
16: 0.3041604
17: 0.2932989
18: 0.2833665
19: 0.2742425
20: 0.2658264
21: 0.2580325
22: 0.2507905
23: 0.2440391
24: 0.2377262
25: 0.2318069
26: 0.2262425
27: 0.2209991
28: 0.2160473
29: 0.2113612
30: 0.2069184
31: 0.2026974
32: 0.1986814
33: 0.1948541
34: 0.1912011
35: 0.1877096
36: 0.1843679
37: 0.1811657
38: 0.1780934
39: 0.1751424
40: 0.1723058
41: 0.1695739
42: 0.1669427
43: 0.1644054
44: 0.1619565
45: 0.1595909
46: 0.1573043
47: 0.1550914
48: 0.1529493
49: 0.1508747


In [17]:
P = U @ V
np.round(P,2)

array([[  8.82, -13.48,   7.  ,  10.84,  10.  ],
       [  9.  , -14.92,   6.  ,  10.77,  10.2 ],
       [  0.54,   9.95,  10.98,   3.28,   0.65],
       [  8.89, -37.65, -16.49,   5.08,  10.  ],
       [  2.65,   4.02,  10.  ,   5.22,   3.03],
       [  5.24,   2.03,  13.98,   8.87,   5.98]])

In [18]:
print(rmse(M,P))

0.15087396453103322


In [19]:
M

array([[nan, nan,  7., nan, 10.],
       [ 9., nan,  6., nan, nan],
       [ 1., 10., nan,  3., nan],
       [ 9., nan, nan,  5., 10.],
       [nan,  4., 10., nan,  3.],
       [ 5.,  2., nan,  9.,  6.]])

In [20]:
np.round(U,2)

array([[ 3.18,  0.5 ],
       [ 3.26,  0.24],
       [ 0.  ,  2.44],
       [ 3.63, -4.88],
       [ 0.81,  1.95],
       [ 1.71,  2.54]])

In [21]:
np.round(V,2)

array([[ 2.74, -4.88,  1.5 ,  3.2 ,  3.11],
       [ 0.22,  4.09,  4.5 ,  1.34,  0.26]])