# Vektoren

In [186]:
import numpy as np

In [190]:
v = np.array([1,2,3])
print(v)

[1 2 3]


In [191]:
w = np.array([[1,2,3]])
print(w)
x = np.array([[1],[2],[3]])
print(x)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [192]:
print(np.shape(v))
print(np.shape(w))
print(np.shape(x))

(3,)
(1, 3)
(3, 1)


In [195]:
print('Zeile', v.shape[0])

Zeile 3


In [199]:
# gib mir die ersten zwei Elemente
print(v[0:2])

[1 2]


In [200]:
# gib mir die letzten beiden Elemente
print(v[1:])

[2 3]


In [202]:
# addition von vektoren
z = np.array([[1], [0], [-1]])
print(z + x)

[[2]
 [2]
 [2]]


In [203]:
# multiplikation von vektoren
print(z * x)

[[ 1]
 [ 0]
 [-3]]


In [204]:
# Länge / Norm / Betrag (L2-Norm = euklidische Norm)
l2Norm = np.linalg.norm(w)
print(l2Norm)

3.7416573867739413


In [205]:
# L-1 Norm (Manhattan Norm)
l1Norm = np.linalg.norm(w, ord=1)
print(l1Norm)

3.0


In [206]:
# Skalarprodukt
print(np.vdot(z, w))

-2


In [208]:
# transponieren
print(np.dot(z.T, z))

[[2]]


In [210]:
# Zwischenwinkel
cos = np.vdot(z, w) / (np.linalg.norm(z) * np.linalg.norm(w))
print(np.arccos(cos) * 180 / np.pi)

112.2076542985965


# Matrizen

In [212]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [214]:
print('Null Matrix')
print(np.zeros([3,4]))

print('Eins Matrix')
print(np.ones([3,4]))

print('Einheitsmatrix')
print(np.eye(5))

print('Diagonalmatrix')
print(np.diag([1,2,3]))

Null Matrix
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Eins Matrix
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Einheitsmatrix
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonalmatrix
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [216]:
# Transponieren
print(A)
print(A.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [218]:
# Matrizen multiplikation
C = np.array([[1,2], [-3, 0]])
D = np.array([[3,5,0], [4,1,1]])
print(np.dot(C, D))
print(C @ D)

[[ 11   7   2]
 [ -9 -15   0]]
[[ 11   7   2]
 [ -9 -15   0]]


Inverse

In [221]:
print(np.linalg.inv(C))
print(np.linalg.inv(C).dot(C))

[[-0.         -0.33333333]
 [ 0.5         0.16666667]]
[[1.00000000e+00 0.00000000e+00]
 [2.77555756e-17 1.00000000e+00]]


In [230]:
# Übung
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(A)
print(np.linalg.inv(A))
# print(np.det(A))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [232]:
# Broadcasting!!
print(np.array([[1,2], [3,4]]) + 2)

[[3 4]
 [5 6]]


In [236]:
print(A + np.array([[1], [0], [2]]))

[[ 2  3  4]
 [ 4  5  6]
 [ 9 10 11]]
